[global]
disable = ["MD013"]

[per-file-ignores]
# The PR template is not a Markdown document in that sense
".github/pull_request_template.md" = ["MD041"]
# The templates may have arbitrary violations as long as the rendered version is compliant
"templates/**" = ["MD024", "MD025", "MD041"]
# The README starts with an image and may include HTML
"README.md" = ["MD033", "MD041"]
