# Copyright (c) 2023 - 2025 Chair for Design Automation, TUM
# Copyright (c) 2025 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: Templating
inputs:
  token:
    description: Token with permissions to create and update pull requests
    required: true
  name:
    description: Stylized name of the package (e.g., "Core" or "DDSIM")
    required: true
  organization:
    description: Name of the repository's organization
    required: true
  project-type:
    description: Type of the project
    required: true
    options:
      - c++-python
      - pure-python
  repository:
    description: Name of the repository
    required: true
  synchronize-contribution-guide:
    description: Whether to synchronize the contribution guide
    default: true
  synchronize-documentation-utilities:
    description: Whether to synchronize documentation utilities such as page.html and custom.css
    default: true
  synchronize-installation-guide:
    description: Whether to synchronize the installation guide
    default: true
  synchronize-issue-templates:
    description: Whether to synchronize the issue templates
    default: true
  synchronize-pull-request-template:
    description: Whether to synchronize the pull-request template
    default: true
  synchronize-release-drafter-template:
    description: Whether to synchronize the Release Drafter template
    default: true
  synchronize-renovate-config:
    description: Whether to synchronize the Renovate configuration
    default: true
  synchronize-security-policy:
    description: Whether to synchronize the security policy
    default: true
  synchronize-support-resources:
    description: Whether to synchronize the support resources
    default: true
  release-drafter-categories:
    description: Release Drafter categories as a JSON string. If empty, a reasonable default will be used
    default: ""
runs:
  using: composite
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - name: Install latest version of uv
      uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b # v6
    - name: Run the templating script
      shell: bash
      env:
        NAME: ${{ inputs.name }}
        ORGANIZATION: ${{ inputs.organization }}
        PROJECT_TYPE: ${{ inputs.project-type }}
        REPOSITORY: ${{ inputs.repository }}
        SYNCHRONIZE_CONTRIBUTION_GUIDE: ${{ inputs.synchronize-contribution-guide }}
        SYNCHRONIZE_DOCUMENTATION_UTILITIES: ${{ inputs.synchronize-documentation-utilities }}
        SYNCHRONIZE_INSTALLATION_GUIDE: ${{ inputs.synchronize-installation-guide }}
        SYNCHRONIZE_ISSUE_TEMPLATES: ${{ inputs.synchronize-issue-templates }}
        SYNCHRONIZE_PULL_REQUEST_TEMPLATE: ${{ inputs.synchronize-pull-request-template }}
        SYNCHRONIZE_RELEASE_DRAFTER_TEMPLATE: ${{ inputs.synchronize-release-drafter-template }}
        SYNCHRONIZE_RENOVATE_CONFIG: ${{ inputs.synchronize-renovate-config }}
        SYNCHRONIZE_SECURITY_POLICY: ${{ inputs.synchronize-security-policy }}
        SYNCHRONIZE_SUPPORT_RESOURCES: ${{ inputs.synchronize-support-resources }}
        RELEASE_DRAFTER_CATEGORIES: ${{ inputs.release-drafter-categories }}
      run: |
        uv run $GITHUB_ACTION_PATH/src/run.py \
          --name $NAME \
          --organization $ORGANIZATION \
          --project_type $PROJECT_TYPE \
          --repository $REPOSITORY \
          --synchronize_contribution_guide $SYNCHRONIZE_CONTRIBUTION_GUIDE \
          --synchronize_documentation_utilities $SYNCHRONIZE_DOCUMENTATION_UTILITIES \
          --synchronize_installation_guide $SYNCHRONIZE_INSTALLATION_GUIDE \
          --synchronize_issue_templates $SYNCHRONIZE_ISSUE_TEMPLATES \
          --synchronize_pull_request_template $SYNCHRONIZE_PULL_REQUEST_TEMPLATE \
          --synchronize_release_drafter_template $SYNCHRONIZE_RELEASE_DRAFTER_TEMPLATE \
          --synchronize_renovate_config $SYNCHRONIZE_RENOVATE_CONFIG \
          --synchronize_security_policy $SYNCHRONIZE_SECURITY_POLICY \
          --synchronize_support_resources $SYNCHRONIZE_SUPPORT_RESOURCES \
          --release_drafter_categories $RELEASE_DRAFTER_CATEGORIES
    - name: Create pull request
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
      with:
        token: ${{ inputs.token }}
        commit-message: ðŸ“ Update templated files
        title: ðŸ“ Update templated files
        body: |
          This pull request updates the files in this repository with the latest changes from the MQT Templates repository.
          For details on the respective changes, see the [changelog](https://github.com/munich-quantum-toolkit/templates/blob/main/CHANGELOG.md) as well as the [upgrade guide](https://github.com/munich-quantum-toolkit/templates/blob/main/UPGRADING.md).

          > [!NOTE]
          > This pull request may contain merge conflicts if there have been changes to a templated file and its template.
          > Resolve such conflicts manually before merging the pull request.
        branch: update-mqt-templates
        base: main
        labels: "documentation"
        sign-commits: true
